version: '3'
services:
  db:
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customer_db
    restart: always
    logging:
      options:
        max-size: 10m
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d customer_db'" ]
      interval: 15s
      timeout: 3s
      retries: 10
    networks:
      - a-geld
  
  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    logging:
      options:
        max-size: 10m
    restart: always
    networks:
      - a-geld

  minio:
    image: minio/minio:latest
    container_name: minio
    networks:
      - a-geld
    environment:
      - MINIO_ROOT_USER=ageld
      - MINIO_ROOT_PASSWORD=ageldAdmin
    command: server ~/minio --console-address :9091
    ports:
      - '9091:9091'
      - '9000:9000'


networks:
  a-geld:
    external: true