include:
  - component: git.astondevs.ru/infrastructure/devops/gitlab-components/build-java-project/gradlew-build-template@0.0.4
    inputs:
      stage: build
      image: gradle:8.6-jdk17-alpine
      artifacts: build/libs/*SNAPSHOT.jar
      rules: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == "develop"
  - component: git.astondevs.ru/infrastructure/devops/gitlab-components/build-docker-image/build-docker-template@0.0.16
  - component: git.astondevs.ru/infrastructure/devops/gitlab-components/deploy-project/deploy-via-compose-template@0.0.11
    inputs:
      rules: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == "develop"


build-app:
  extends: .gradlew-build-template
  script:
    - gradle assemble

create-container:
  extends: .build-docker-template
  needs:
    - build-app
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == "develop"
  
deploy-dev:
  extends: .deploy-via-compose
  variables:
    EXPOSE_HOST_PORT: "8083"
    EXPOSE_CONTAINER_PORT: "8083"
  tags:
    - shell-dev
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

deploy-prod:
  extends: .deploy-via-compose
  variables:
    EXPOSE_HOST_PORT: "8083"
    EXPOSE_CONTAINER_PORT: "8083"
  tags:
    - shell-prod
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
