version: '3'

services:

  db:
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=customer_db
    restart: always

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    restart: always

  config-service:
    image: config-service:latest
    ports:
      - "8888:8888"
    restart: always

  discovery-service:
    image: discovery-service:latest
    ports:
      - "8761:8761"
    restart: always
    depends_on:
      - config-service

  api-gateway:
    image: api-gateway:latest
    ports:
      - "8082:8082"
    restart: always
    depends_on:
      - discovery-service

  customer-service:
    image: customer-service:latest
    ports:
      - "8084:8084"
    restart: always
    depends_on:
      - api-gateway
      - db
      - redis
